In [1]:
import numpy as np

In [2]:
data = np.loadtxt("D:\DS\Chapter 1\populations.txt")
data

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\pratik.magdum\AppData\Local\Temp\ipykernel_12568\3460005479.py:1: SyntaxWarning: invalid escape sequence '\D'
  data = np.loadtxt("D:\DS\Chapter 1\populations.txt")


array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [3]:
year, hare, lynx, carrot = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [9]:
# mean population
# data [row , column]
# taking from 1st column
population = data[:,1:]
print(population)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [10]:
# Standard Deviation
population.std(axis = 0)

array([20897.90645809, 16254.59153691,  3322.50622558])

* In NumPy, argmax() is a function used to find the index of the maximum value in an array.

In [ ]:
arr = np.array([10, 20, 5, 40])
index = np.argmax(arr)
print(index)  # Output: 3

In [12]:
np.argmax(population, axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

* Broadcasting in NumPy is a powerful feature that allows arithmetic operations on arrays of different shapes. It works by automatically expanding the smaller array so that it has the same shape as the larger one—without actually copying data.


In [13]:
a = np.array([1,2,3])
b = 10
print(a+b)

[11 12 13]


In [15]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
print(a+b)

[[11 22 33]
 [14 25 36]]


* The np.tile() function in NumPy constructs a new array by repeating an input array. It is often used for creating repeated patterns or preparing arrays for broadcasting.

* numpy.tile(A, reps)

* 
A: Input array.
reps: Number of repetitions of A along each axis (can be an int or tuple).


# np.tile(..., (3, 1))
This means:
Repeat the array 3 times along the row axis (axis 0),
Repeat 1 time along the column axis (axis 1).
Think of the original 1D array [0, 10, 20, 30] as a row. Tiling it with (3, 1) will stack it vertically 3 times:

In [37]:
np.arange(0,40,10)

array([ 0, 10, 20, 30])

In [16]:
t= np.tile(np.arange(0,40,10), (3,1))
print(t)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [17]:
t= np.tile(np.arange(0,40,10), (3,2))
print(t)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [18]:
t= np.tile(np.arange(0,40,10), (4,2))
print(t)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [19]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [22]:
# converts 1D array to 2D array here
a = a[:,np.newaxis]
a.shape

(4, 1, 1)

In [21]:
a

array([[ 0],
       [10],
       [20],
       [30]])

# Array Manipulation

* Flattening

* The ravel() function returns a flattened (1D) version of an array. 

In [25]:
a = np.array([[1,2,3],[4,5,6]])
b = a.ravel()
print(b)

[1 2 3 4 5 6]


* reshape() is used to change the shape of an array without changing its data.
* numpy.reshape(a, newshape)

In [26]:
c = b.reshape(3,2)
print(c)

[[1 2]
 [3 4]
 [5 6]]


# Sort

In [30]:
a = np.array([[6,5,4], [8,9,41]])
a = np.sort(a, axis = 1)
print(a)

[[ 4  5  6]
 [ 8  9 41]]


In [31]:
a = np.array([[6,5,4], [8,9,41]])
a.sort(axis = 1)
a

array([[ 4,  5,  6],
       [ 8,  9, 41]])

# Fancy Indexing

In [33]:
# Fancy indexing is a powerful NumPy feature that allows you to access or modify array elements using arrays or lists of indices, rather than just slices.

In [35]:
a = np.array([4,3,7,1])
index = np.argsort(a)
index

array([3, 1, 0, 2])

In [36]:
a[index]

array([1, 3, 4, 7])